### ISSUE TITLE
Cannot get RESULT_STORAGE working

### ISSUE THREAD

**Issue by peterwake** [thumbor-community/aws#126]
Hi,

I can't get thumbor aws to save into the aws `thumbor_result_storage` folder. I'm using the settings below to build a Cloud66 instance from docker image `apsl/thumbor:latest` (at https://hub.docker.com/r/apsl/thumbor/). When I request a thumbnail of a very large (90MB) image e.g. https://myurl.com/unsafe/128x0/mybucket/myfile.jpg, then go into AWS and look at my S3 `EU_CENTRAL_1_THUMBS_S3_BUCKET` bucket, I have a 9MB image in the `thumbor_storage` folder, but nothing in the `thumbor_result_storage` folder. Also, the returned image is a whopping 693KB rather than the expected ~5KB. Does anyone have any suggestions?

Thanks and regards
PeteW

```
version: 2
services:
  eu-central-1:
    image: apsl/thumbor:latest
    ports:
    - 8000:80:443
    volumes:
    - "/tmp/eu-central-data:/data"
    log_folder: "/logs"
    env_vars:
      AWS_ACCESS_KEY_ID: _env(EU_CENTRAL_1_AWS_ACCESS_KEY_ID)
      AWS_SECRET_ACCESS_KEY: _env(EU_CENTRAL_1_AWS_SECRET_ACCESS_KEY)
      TC_AWS_REGION: eu-central-1
      LOADER: tc_aws.loaders.presigning_loader
      TC_AWS_STORAGE_BUCKET: _env(EU_CENTRAL_1_THUMBS_S3_BUCKET)
      TC_AWS_STORAGE_ROOT_PATH: thumbor_storage
      TC_AWS_RESULT_STORAGE_BUCKET: _env(EU_CENTRAL_1_THUMBS_S3_BUCKET)
      TC_AWS_RESULT_STORAGE_ROOT_PATH: thumbor_result_storage
      STORAGE: tc_aws.storages.s3_storage
      UPLOAD_PHOTO_STORAGE: tc_aws.storages.s3_storage
      RESULT_STORAGE: tc_aws.result_storages.s3_storage
      STORAGE_EXPIRATION_SECONDS: 0
      RESULT_STORAGE_EXPIRATION_SECONDS: 0
      MAX_PIXELS: 200000000
```
